### ISSUE TITLE
transformation logic entered in dynamodb works for first data source but not for second data source

### ISSUE THREAD

**Issue by AditModi** [aws-samples/aws-cdk-pipelines-datalake-etl#10]
> "Make sure the transformation logic is entered in dynamodb for <> table" 

Where to enter the transformation logic ?  
 a dynamodb table is created as part of cdk-pipelines. should a new item be created in that table?

**Comment by zahidali-aws** [comment]
Script should be included in mentioned library path: lib/glue_scripts/transformation-sql/

and will be used in in glue script as per mentioned snippet. Please note these paths are passed as part of Glue job parameters and read from arguments

    prefix = args['txn_sql_prefix_path']
    key = prefix[1:] + args['table_name'] + '.sql'
